Login frontend 2
wolox-training/fo-android pull request #2
Opened 2018-04-04 14:42 UTC by foviedoITBA

# Summary

Added login validation and user credentials storage

# Screenshot
![screenshot_1522852850](https://user-images.githubusercontent.com/15112133/38314642-17d72c8e-37fd-11e8-81ba-3f9960fda758.png)

# Trello Card

https://trello.com/c/9hZ0VKVb/19-u1-frontend-login-validaciones

2018-04-04 15:45 UTC, alvarez-fabian requested changes
Nice work. A couple of comments, but only small things :smiley:. Love how you validated the fields, keep it up :+1:.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/BlankActivity.java
> +        ((TextView)findViewById(R.id.welcome_message)).setText(
Here you should use [ButterKnife](http://jakewharton.github.io/butterknife/) to bind the views. Like this:
```
@BindView(R.id.welcome_message) TextView mWelcomeTextView;
```
And remove the `findViewById`. You don't need to call `Butterknife.bind()` because `WolmoActivity` already does that for you :+1:.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/BlankActivity.java
> +                .getString(getString(R.string.sp_key_email), "generic@wolox.com.ar")
This should be `null` or maybe trow a exception or show a toast if no user is found. (We are not supposed to enter to this activity if there is no user saved).

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/BlankActivity.java
> +public class BlankActivity extends Activity {
Extend from `WolmoActivity` that implements some methods to remove duplicated code and simplify things. :smile:

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
>  public class LoginActivity extends Activity {
Same here, now we should use `WolmoActivity`

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +    private EditText mEmailField;
Same as the other comment, you should change this to use `ButterKnife`. Consider that you need to change the visibility of those fields because butterknife cannot bind private members.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +        mLoginButton.setOnClickListener((v) -> {
Another thing you can use from butterknife is the `OnClick` annotation. Create a method and annotate it with `@OnClick(R.id.id_of_the_view)` and this will create the click listener an call this method when the view is clicked:
```
@OnClick(R.id.login_button)
void onLoginButtonClicked() {
    ....
}
```
This way you don't need to set basic listeners and clean up the code :smile: 

If you don't want to use that method, you could override `setListeners()` from `WolmoActivity` to set the listeners and clean up `onCreate()`.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +            String password = mPasswordField.getText().toString();
If you don't need to modify those strings, you could make them `final`. (Non blocker, but a nice thing to do).

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +            List<Validation<String>> emailValidationList = new LinkedList<>();
You should extract this block of code to another method, like: `private boolean isValidMail() { ... }`.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +            List<Validation<String>> passwordValidationList = new LinkedList<>();
Same here, better to keep small methods with single responsibility when possible :smile:

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +            if (formIsValid) {
You can change this to `if (isValidEmail() && isValidPassword())`  or something like that.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmailFormatValidation.java
> +        boolean ok = email.matches("(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\
Here you can use `Patterns.EMAIL_ADDRESS` from `android.util`. (Also it'll be better to make the regex constant and put it in the top of the class).

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyEmailValidation.java
> +            errorMessage = TrainingApplication.getContext().getResources().getString(R.string.empty_email);
Here instead of accessing the `TrainingApplication` statically you should "inject" the context needed for this Validation in the constructor. Beware that this works fine in this case because you don't share a Validator instance between screens or classes, otherwise that could cause a memory leak.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyPasswordValidation.java
> +            errorMessage = TrainingApplication.getContext().getResources().getString(R.string.empty_password);
Same here :smile:

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyPasswordValidation.java
> +        boolean ok = !(password.length() == 0);
You can use `TextUtils.isEmpty()` that's null safe.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyEmailValidation.java
> +        boolean ok = !(email.length() == 0);
You can use TextUtils.isEmpty() that's null safe.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/Validation.java
> +public interface Validation<T> {
I love how you implemented the validations. Just an extra, for this kind of utils it'll be awesome to add a `javadoc` describing why is this class used and how to use it.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/Validation.java
> +    public ValidationResult validate(T objectToValidate);
Same here, just the `public` methods, though. Also you don't need to declare the method as `public` :smile:, the compiler knows it's public because you are inside an interface.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/email_field"
It's a good practice to prefix the views with the name of the parent fragment or activity. This way we avoid id collisions. Example: `activity_login_email_field` or `login_email_field`.  Same for the other IDs.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/res/values/strings.xml
> +    <string name="empty_email">You must provide an email</string>
You could rename this to `empty_email_error` and the same for the other errors.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/res/values/strings.xml
> +    <string name="sp_default">ar.com.wolox.android.foandroid.SP_DEFAULT</string>
This kind of constant should be placed in a `Configuration` class or the class that use it, you can use `BaseConfiguration` that already exists. 
In general we call an external company to translate the strings and they could try to translate this one and the app will not work as expected.
We use `strings.xml` only for the text that we show to the users and should/can be translatable.

2018-04-04 15:45 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyPasswordValidation.java
> +
Extra empty line :stuck_out_tongue_closed_eyes:

2018-04-06 14:07 UTC, foviedoITBA commented on app/src/main/res/values/strings.xml
> +    <string name="sp_default">ar.com.wolox.android.foandroid.SP_DEFAULT</string>
I didn't find any best practices listed, but the Android docs use these string as keys:
https://developer.android.com/training/data-storage/shared-preferences.html
I changed it as requested anyways.

2018-04-06 14:08 UTC, foviedoITBA commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyEmailValidation.java
> +            errorMessage = TrainingApplication.getContext().getResources().getString(R.string.empty_email);
Please explain how a memory leak would be caused.

2018-04-06 14:54 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyEmailValidation.java
> +            errorMessage = TrainingApplication.getContext().getResources().getString(R.string.empty_email);
It depends of what `Context` do you use. For example you could use an `Activity` as a context. If you share the instance of the validation with another `Activity` and finish the current, you'll have a reference to the "dead" activity (and all child fragments and views) in the validation and thew will not be garbage collected.
If you keep doing that for a couple more of Activities the application will crash.
That's the reason you should not send the activity or a view reference to a background thread/task.

2018-04-06 15:01 UTC, alvarez-fabian commented on app/src/main/res/values/strings.xml
> +    <string name="sp_default">ar.com.wolox.android.foandroid.SP_DEFAULT</string>
Yeah, we don't put that kind of strings in `string.xml` here in Wolox because we had that problem before with previous applications and it's annoying to fix. But you're right, google examples are different. We could discuss in the android meeting what could be the best way to handle that. :+1:

2018-04-06 15:16 UTC, alvarez-fabian requested changes
Sorry for commenting again :disappointed: Just a couple of changes and we are ready to go.

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +        final String savedEmail = getSharedPreferences(SP_DEFAULT, Context.MODE_PRIVATE)
You can move this lines to `init()` to avoid overriding `onCreate()`.

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/BlankActivity.java
> +        mWelcomeMessage.setText(
You should move this logic to `init()` so we can avoid overriding `onCreate` and we don't have an empty method.

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +            startActivity(new Intent(this, BlankActivity.class));
What happens if you press back in the `BlankActivity`? Can you go back to the login? You shouldn't be able to.
You could use:
```
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
```
to clear the backstack.

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +            startActivity(new Intent(this, BlankActivity.class));
Same here, you shouldn't be able to go back once you logged in.

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +    private List<Validation<String>> passwordValidationList = buildPasswordValidationList();
Question, do you keep the lists here for a reason?
If not, you could move them to the top of the class.

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmailFormatValidation.java
> +    public EmailFormatValidation (Context c) {
When possible, try to use the a more descriptive name for the parameters.

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyEmailValidation.java
> +    public EmptyEmailValidation(Context c) {
Same here :smile:

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/EmptyPasswordValidation.java
> +        mContext = c;
And here

2018-04-06 15:16 UTC, alvarez-fabian commented on app/src/main/java/ar/com/wolox/android/foandroid/validations/Validation.java
> + * @param <T>   The type of object that this Validation validates.
Wow, love it! This helps a lot when someone else (or you in the future) needs to update the code.

2018-04-06 15:38 UTC, foviedoITBA commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/LoginActivity.java
> +    private List<Validation<String>> passwordValidationList = buildPasswordValidationList();
I tend to keep private fields at the bottom since they're not part of the interface, but I'll move it upwards.

2018-04-06 15:50 UTC, alvarez-fabian approved these changes
Remember to Squash and merge :+1:.
![dance](https://media.giphy.com/media/jzaZ23z45UxK8/giphy.gif)

2018-04-06 15:52 UTC, merged