Home page news front
wolox-training/fo-android pull request #8
Opened 2018-04-18 15:37 UTC by foviedoITBA

# Sumary
Implemented front-end for news list

# Screenshot
![screenshot_1524065167](https://user-images.githubusercontent.com/15112133/38941869-dfe1dc72-4303-11e8-9fbc-91fef41d80ee.png)

# Trello card
https://trello.com/c/bZfA6BPT/9-u4-home-page-frontend-news

# Additional coments
* The 'time ago' field is not i18n or 'l10n' and I couldn't change it
* The FAB button doesn't take the color from the App's style colorAccent field as the documentation states (https://developer.android.com/guide/topics/ui/floating-action-button.html#CreateFAB), so backgroundTint (API level >= 21) is used
* According to the material design guidelines, the FAB button shouldn't disappear in the same direction as the tab switch (https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior). Should I change it?

2018-04-18 16:58 UTC, DemianIac requested changes
Great work Fernan just a few minor things.

About your comments:
"The 'time ago' field is not i18n or 'l10n' and I couldn't change it"
Don't you worry for this now

"The FAB button doesn't take the color from the App's style colorAccent field as the documentation states (https://developer.android.com/guide/topics/ui/floating-action-button.html#CreateFAB), so backgroundTint (API level >= 21) is used "
Are you sure that you don't replace the theme style of the app? . I will check this later sounds weird

"According to the material design guidelines, the FAB button shouldn't disappear in the same direction as the tab switch (https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior). Should I change it?"
Just make sure than the animation hides the FAB when you scroll down , and shows it again when you scroll up.
Don't take any action to hide the button when you change of tab (Make sure that if the button is hide and you switch from tab and return , to make it visible again)

"The FAB recommended on the Trello card is deprecated" 
Yes I know but it's easier for people to start interacting with this view. We should use the official one of course. I will add a link for new training . 

Let me know if you have any questions at all
Thanks!.

2018-04-18 16:58 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/NewsFragment.java
> +    private static class NewsAdapter extends RecyclerView.Adapter {
We should create a new file with this class.We can have an adapter package with this file to keep visibility of the different resources that we have available

2018-04-18 16:58 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/NewsFragment.java
> +    private RecyclerView mRecyclerView;
We have avaible [http://jakewharton.github.io/butterknife/](Butterknife) in Wolmo. Try yo use it , to keep the code clean. from findViewById on the onCreateView

2018-04-18 16:58 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/NewsFragment.java
> +            TextView mTitle;
You can use ButterKnife here too. In this case it's not initialized by Wolmo , so you need to bind the view according to the docs

2018-04-18 16:58 UTC, DemianIac commented on app/src/main/res/layout/news_list_item.xml
> +        android:background="@null"
Any reason to add this?

2018-04-18 16:58 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/NewsFragment.java
> +        private int mVisibleThreshold = 5;
You only need a constant for this . In the future maybe you are going to take this value from config.

2018-04-18 16:58 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/NewsFragment.java
> +        for (int i = 0; i < 10; i++) {
Remember to add a //TODO comment to remove things like these for testing.

2018-04-20 12:53 UTC, foviedoITBA commented on app/src/main/res/layout/news_list_item.xml
> +        android:background="@null"
I don't know what you mean by "this". That's the little heart button and it's part of the design guidelines.

2018-04-20 12:53 UTC, foviedoITBA commented on app/src/main/java/ar/com/wolox/android/foandroid/ui/NewsFragment.java
> +        private int mVisibleThreshold = 5;
I actually thought that it shouldn't be a constant in order to provide certain flexibility (maybe the threshold could change over time or within fragments, since the adapter is reusable). I'll make it constant anyways.

2018-04-25 17:55 UTC, DemianIac commented on app/src/main/res/layout/news_list_item.xml
> +        android:background="@null"
You are right . My question was for the android:background="@null"

2018-04-25 17:57 UTC, DemianIac approved these changes
:+1:  Awesome work Fernan! , just check my comment on the view . :clap:

2018-05-24 17:53 UTC, merged